### PR TITLE
Check if record exists

### LINKED ISSUE #3: Create record when it does not exist
Currently the program panics when the DNS record does not yet exist:
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/paulopacitti/bacon/cmd.retrieveDNS({{0xc000106140, 0x44}, {0xc000106190, 0x44}, {0xc0000b09c0, 0x9}, {0xbe9080, 0x1}, {0xbe8f48, 0x1}})
        /root/go/pkg/mod/github.com/paulopacitti/bacon@v0.1.0/cmd/update.go:138 +0x4cb
github.com/paulopacitti/bacon/cmd.runUpdate(0xc0000aeb00?, {0x89e5a3?, 0x4?, 0x89e5a7?})
        /root/go/pkg/mod/github.com/paulopacitti/bacon@v0.1.0/cmd/update.go:203 +0x198
github.com/spf13/cobra.(*Command).execute(0xc181c0, {0xc7e4a0, 0x0, 0x0})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x882
github.com/spf13/cobra.(*Command).ExecuteC(0xc17ee0)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/paulopacitti/bacon/cmd.Execute()
        /root/go/pkg/mod/github.com/paulopacitti/bacon@v0.1.0/cmd/root.go:17 +0x1a
main.main()
        /root/go/pkg/mod/github.com/paulopacitti/bacon@v0.1.0/main.go:8 +0xf
```
Would be nice to handle this error by either creating it automatically or printing a more user friendly error.

### PR DESCRIPTION
**Pull request by mtricht**
If not, print out friendly message saying it is missing. Closes #3

### CODE REVIEW

File: cmd/update.go [hunk 1]
```diff
@@ -135,6 +135,10 @@ func retrieveDNS(c Config) (string, error) {
 		return "", fmt.Errorf("error retrieving DNS: %s", result.Status)
 	}
 
+	if len(result.Records) == 0 {
```
Comment (paulopacitti) [inline cmd/update.go:138]: I think placing this block before the `if result.Status == "ERROR"` will be better, otherwise, if there's an Error and no records were found, the first conditional won't be too specific in the error message on why that happened

**Review by paulopacitti — CHANGES_REQUESTED** [review]
Thanks for your work, I left a comment :)

File: cmd/update.go (hunk 1 above)
Comment (mtricht) [reply cmd/update.go:138]: That could be misleading though if there's a different error. Records will most likely always be zero when there is an error.

Check your email btw.

Comment (paulopacitti) [reply cmd/update.go:138]: you're actually right, the error verification should precede the DNS records length check. It's alright then
